
%define         module	pymetar

Summary:	Module that provides access to NOAA's METAR weather reports
Summary(pl):	Modu³ do pobierania danych pogodowych METAR
Name:		python-%{module}
Version:	0.8
Release:	1
License:	GPL
Group:		Development/Languages/Python
Source0:	http://www.schwarzvogel.de/pkgs/%{module}-%{version}.tar.gz
# Source0-md5:	228eedaddc7821f2ed086d91f9d56b68
URL:		http://www.schwarzvogel.de/software-pymetar.shtml
%pyrequires_eq	python-modules
BuildRequires:	python-devel >= 2.3
BuildRequires:	rpm-pythonprov
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
The National Oceanic and Atmospheric Administration (NOAA,
www.noaa.gov) provides easy access to the weather reports generated by
a large number of weather stations (mostly at airports) worldwide.
Those reports are called METAR reports and are delivered as plain text
files.

While this is convenient if you just want to quickly look up the data,
there's some effort involved in parsing all of this into a format that
is digestible by a program. Plus, you have to remember the base URL of
the reports and fetch the file.

The library provides a large number of methods to fetch the parsed
information in a plethora of formats. Those functions are described in
the file librarydoc.txt which was in turn generated using PyDoc.

%description -l pl
NOAA (Narodowa Administracja Oceaniczna i Atmosferyczna, www.noaa.gov)
udostêpnia raporty pogodowe generowane przez wiele stacji pogodowych z
ca³ego ¶wiata. Raporty te nazywane s± raportami METAR i udostêpniane w
postaci plików tekstowych.

Jest to wygodne je¶li chce siê szybko przejrzeæ dane. Jednak
przetwarzanie ich mo¿e byæ k³opotliwe. Dodatkowo, trzeba pamiêtaæ
adres pliku z danej stacji pogodowej.

Biblioteka ta udostêpnia wiele metod, które udostêpniaj± dane
przetworzone z raportów METAR.

%prep
%setup -q -n %{module}-%{version}

%build
CFLAGS="%{rpmcflags}"
export CFLAGS
python setup.py build

%install
rm -rf $RPM_BUILD_ROOT
python setup.py install \
        --root=$RPM_BUILD_ROOT --optimize=2

rm -f $RPM_BUILD_ROOT%{py_sitedir}/%{module}.py

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc README THANKS TODO
%attr(755,root,root) %{_bindir}/*
%{py_sitedir}/*.py[co]
